Update generate.py - fix case-sensitive variable call
The current version of bittensor references the wallet as "Wallet" (with a capital "W").  generate.py defines wallet as "bittensor.wallet" and thus throws the error "AttributeError: module 'bittensor' has no attribute 'wallet'. Did you mean: 'Wallet'?".  This PR updates the definition to "bittensor.Wallet".